### ISSUE TITLE
Dynamic OG won't show image but only content

### ISSUE THREAD

**Issue by AndlerRL** [bitcashorg/masterbots#242]
After testing this route -> https://dev.masterbots.ai/healthcare/9407d946-8226-469b-86a2-b78e26c98b89 I encountered some issues rendering the image. The route is fine however, the image URL might not be right hence it is not returning a valid image. Also, the content is not shorted to up to 160 characters (up to 3 lines of text).

See this for details: https://www.opengraph.xyz/url/https%3A%2F%2Fdev.masterbots.ai%2Fhealthcare%2F9407d946-8226-469b-86a2-b78e26c98b89

> **PRO TIP:** Try to test the site metadata with either **ngrok** or by putting your private IP in order to see the metadata to pop-up on the OG web tool.

**Comment by sheriffjimoh** [comment]
The problem with the og image is that the VERCEL_URL  is returning this "https://masterbots-eokchzmre-bitcash.vercel.app/masterbots-eokchzmre-bitcash.vercel.app" instead of one of these
<img width="912" alt="Screenshot 2024-07-09 at 10 52 42 PM" src="https://github.com/bitcashorg/masterbots/assets/63134009/ae64a7e6-18dc-475b-9c8f-9dfefdd4d0e4">
 🤔

**Comment by AndlerRL** [comment]
Yeah, we will need then to change to another env var as you communicated previously, so the OG or anything that depends on the "VERCEL_URL" won't have this issue.

**Comment by AndlerRL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OG Dynamic Image Not Showing On Prod & Dev Enviroments](https://trello.com/c/uK6HeCSD/186-og-dynamic-image-not-showing-on-prod-dev-enviroments)
